[PLOP-1043]Add the new rules for some and the match with the previous linter
studyportals/CodeStyle pull request #27
Opened 2020-11-20 14:59 UTC by MikePv

2020-11-23 16:58 UTC, frankkluijtmans commented on .scss-lint.yml
> +  #"selector-max-id": 0   NOT SURE
I would skip this one in the new config. 0 is certainly a bad option since that would completely disallow ID's in selectors.

2020-11-23 16:58 UTC, frankkluijtmans commented on .scss-lint.yml
> +  #
No need to have this rul in my opinion. Sometimes when we write some odd css rules that are needed for a specific usecase we like to have a comment to explain our css rule.

2020-11-23 16:58 UTC, frankkluijtmans commented on .scss-lint.yml
> +  #
Enforcing a certain type of property sorting would very likely cause problems and doesn't necessarily give added value. What do you think @stefanklokgieters ?

2020-11-24 08:07 UTC, stefanklokgieters requested changes

2020-11-24 08:07 UTC, stefanklokgieters commented on .scss-lint.yml
> +  #
Agreed

2020-11-24 08:07 UTC, stefanklokgieters commented on .scss-lint.yml
> +  #
Fully agree

2020-11-24 08:32 UTC, MikePv commented
@stefanklokgieters @frankkluijtmans what about the NameFormat, SelectorFormat and ImportPath rules? I did not find a 1to1 match with the new linter. I will put the links to the rules below.

[Old rules](https://github.com/sds/scss-lint/tree/master/lib/scss_lint/linter)

[New rules](https://stylelint.io/user-guide/rules/list)

2020-11-24 15:24 UTC, stefanklokgieters commented
@MikePv just checked the documentation and I think that `NameFormat` and `SelectorFormat` don' have to be forced by the linter. I do like the SCSS partial distinguishment with a required underscore for `ImportPath` as it indicated you are importing a partial file. @frankkluijtmans what do you think?

2020-11-26 09:12 UTC, frankkluijtmans commented
@MikePv We've had a look at the NameFormat, SelectorFormat and ImportPath rules. NameFormat and SelectorFormat are a bit too stylistic to take into this overall config and for ImportPath there is no available replacement in stylint's default ruleset. So I'd say let's skip them.

2020-11-26 09:13 UTC, frankkluijtmans approved these changes

2020-11-26 09:13 UTC, frankkluijtmans requested changes
Can we get rid of the commented lines now?

2020-11-26 11:01 UTC, MikePv commented
> Can we get rid of the commented lines now?

Done

2020-11-26 11:03 UTC, stefanklokgieters approved these changes

2020-11-26 11:04 UTC, frankkluijtmans approved these changes

2020-11-26 11:10 UTC, merged