MIAUW-5614 - CodeStyle repository documentation
studyportals/CodeStyle pull request #37
Opened 2021-08-16 14:19 UTC by frankkluijtmans

Story:
https://studyportals.atlassian.net/secure/RapidBoard.jspa?rapidView=48&projectKey=MIAUW&modal=detail&selectedIssue=MIAUW-5614

What was done in this pull request?:
- Listed all linters and how to implement them.
- Mentioned super-linters usage of linters inside of this repository.

Note: I didn't go too much into detail on all of the linters, but referenced links to their official docs. Also, I left out details on specific rulesets since that would make the docs too extensive and they would also change too often.

@ external reviewers: I'm asking for some external reviews on my Pull Requests to have some feedback from people who didn't work on the story or necessarily know the entire context since I think this is very valuable to have. If you have some time to leave a review, it would be greatly appreciated! :)

2021-08-16 14:32 UTC, stefanklokgieters approved these changes

2021-08-17 11:40 UTC, juanrivas-sp approved these changes

2021-08-17 12:37 UTC, MikeConsemulder requested changes

2021-08-17 12:37 UTC, MikeConsemulder commented on README.md
> +When you installed the CodeStyle package you can simply *extend* from the ESLint configuration file inside it.
```suggestion
When you install the CodeStyle package you can simply *extend* from the ESLint configuration file inside it.
```

2021-08-17 12:37 UTC, MikeConsemulder commented on README.md
> +[TSLint](https://palantir.github.io/tslint/) is linter that is specifically meant to lint TypeScript code. When you installed the CodeStyle package you can simply *extend* from the TSLint configurati
```suggestion
[TSLint](https://palantir.github.io/tslint/) is a linter that is specifically meant to lint TypeScript code. When you install the CodeStyle package you can simply *extend* from the TSLint configuration file inside it.
```

2021-08-17 12:37 UTC, MikeConsemulder commented on README.md
> +[StyleLint](https://stylelint.io/) is our main linter for all styling related files. It can read all types of style related syntax, like SCSS, Sass, Less and SugarSS. When you installed the CodeStyle
```suggestion
[StyleLint](https://stylelint.io/) is our main linter for all styling related files. It can read all types of style related syntax, like SCSS, Sass, Less and SugarSS. When you install the CodeStyle package you can simply *extend* from the StyleLint configuration file inside it.
```

2021-08-17 12:37 UTC, MikeConsemulder commented on README.md
> +[SCSSLint](https://github.com/sds/scss-lint) is a linter specifically meant for running against rulesets that are specific to `.scss` files. Generally though, we prefer to use [StyleLint](#stylelint)
```suggestion
[SCSSLint](https://github.com/sds/scss-lint) is a linter specifically meant for running against rulesets that are specific to `.scss` files. Generally though, we prefer to use [StyleLint](#stylelint) since it supports SCSS natively. When you install the CodeStyle package you can simply reference the SCSSLint configuration file inside it from your custom configuration.
```

2021-08-17 12:37 UTC, MikeConsemulder commented on README.md
> +[PHPMD](https://phpmd.org/) (or PHP Mess Detector) is a linter for PHP files. It takes a given PHP source code base and look for several potential problems within that source. When you installed the
```suggestion
[PHPMD](https://phpmd.org/) (or PHP Mess Detector) is a linter for PHP files. It takes a given PHP source code base and look for several potential problems within that source. When you install the CodeStyle package you can reference the PHPMD configuration file inside it.
```

2021-08-17 12:58 UTC, MikeConsemulder approved these changes

2021-08-17 13:36 UTC, stefanklokgieters approved these changes

2021-08-18 07:48 UTC, merged